language: python

env:
  - SPHINX_VERSION=2.4.4 TRAVIS_CI=True

python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y doxygen texlive-latex-base texlive-latex-extra texlive-fonts-recommended latexmk

install:
  - pip install flake8
  - pip install nose
  - pip install Sphinx==$SPHINX_VERSION
  - pip install .

# Builds all examples & html documentation
#
# Provide definition for DOXYGEN variable to stop it trying
# to run `which doxygen`
script:
  - make DOXYGEN=doxygen DEBUG=""
  - make test
  - make flake8
